Repository nanvix/hal, pull requests merged in 2019-07, with the labels that each got.

#486 [hal] Enhancement: Producer and Consumer Stress Test
  src/test/cluster/cores.c
Labels: enhancement

#487 [lib] 64 Bit Formatted Printing
  src/hal/klib/kvsprintf.c
Labels: enhancement

#488 Feature unix64 traps
  build/unix64/make/makefile
  include/arch/core/linux64.h
  include/arch/core/linux64/trap.h
  include/nanvix/hal/core/trap.h
  src/test/build/makefile.unix64
  src/test/core/syscalls.c
  src/test/main.c
Labels: feature, unix64

#495 [linux64-core] Exception Interface
  include/arch/core/linux64/excp.h
  include/nanvix/hal/core/exception.h
  src/hal/arch/cluster/linux64-cluster/boot.c
  src/hal/arch/cluster/linux64-cluster/cores.c
  src/hal/arch/core/linux64-core/ctx.c
  src/hal/arch/core/linux64-core/excp.c
  src/hal/build/makefile.unix64
  src/test/build/makefile.unix64
  src/test/core/exception.c
  src/test/main.c
Labels: feature, unix64

#496 [linux64-core] Hardware Interrupt Interface
  include/arch/core/linux64/int.h
  src/hal/arch/cluster/linux64-cluster/boot.c
  src/hal/arch/core/linux64-core/int.c
  src/hal/build/makefile.unix64
  src/test/build/makefile.unix64
  src/test/core/interrupt.c
  src/test/main.c
Labels: feature, unix64

#490 [linux64-core] Performance Monitoring Interface
  include/arch/core/linux64.h
  include/arch/core/linux64/perf.h
  src/hal/arch/cluster/linux64-cluster/boot.c
  src/hal/build/makefile.unix64
  src/test/build/makefile.unix64
  src/test/main.c
Labels: feature, unix64

#499 [hal] Generic IO Functions for 8/16/32 bits
  include/arch/core/i486/pmio.h
  include/nanvix/hal/core/pmio.h
Labels: enhancement

#501 [linux64-core] Cache Interface
  src/hal/arch/core/linux64-core/cache.c
  src/hal/arch/core/linux64-core/math.c
Labels: enhancement, unix64

#502 [linux64-cluster] TLB Interface
  src/hal/arch/cluster/linux64-cluster/memory.c
Labels: enhancement, unix64

#503 [linux64-cluster] Cluster Interface
  include/arch/cluster/linux64-cluster.h
  include/arch/cluster/linux64-cluster/_linux64-cluster.h
  include/arch/cluster/linux64-cluster/cores.h
  include/arch/cluster/linux64-cluster/event.h
  include/arch/core/linux64/spinlock.h
  src/hal/arch/cluster/linux64-cluster/boot.c
  src/hal/arch/cluster/linux64-cluster/cluster.c
  src/hal/arch/cluster/linux64-cluster/cores.c
  src/hal/arch/cluster/linux64-cluster/event.c
  src/hal/arch/cluster/riscv32-cluster/cluster.c
  src/hal/build/makefile.unix64
Labels: feature, unix64

#513 [unix64] Improving Documentation
  src/hal/arch/cluster/linux64-cluster/cluster.c
  src/hal/arch/core/linux64-core/cache.c
  src/hal/arch/core/linux64-core/ctx.c
  src/hal/arch/core/linux64-core/mmu.c
Labels: enhancement, unix64

#514 [linux64-cluster] Moving Timer Interface to Cluster AL
  src/hal/arch/cluster/linux64-cluster/timer.c
Labels: enhancement, unix64

#516 [bostan-processor] DMA Data Interface
  include/arch/processor/bostan/noc/ctag.h
  include/arch/processor/bostan/noc/dma.h
  include/arch/processor/bostan/noc/dtag.h
  src/hal/arch/processor/bostan/ctag.c
  src/hal/arch/processor/bostan/dma.c
  src/hal/arch/processor/bostan/dtag.c
  src/test/main.c
  src/test/processor/cnoc.c
  src/test/processor/dnoc.c
  src/test/test.h
Labels: feature
