Repository nanvix/hal, pull requests merged in 2019-08, with the labels that each got.

#517 Generic Cluster Setup
  build/optimsoc/make/makefile
  build/qemu-openrisc/make/makefile
  build/qemu-riscv32/make/makefile
  build/qemu-x86/make/makefile
  build/unix64/make/makefile
  include/arch/cluster/riscv32-cluster/cores.h
  include/arch/core/i486/core.h
  src/build/makefile.nanvix
  src/hal/arch/cluster/k1b-cluster/cluster.c
  src/hal/arch/cluster/linux64-cluster/cluster.c
  src/hal/arch/cluster/or1k-cluster/cluster.c
  src/hal/arch/cluster/or1k-cluster/memory.c
  src/hal/arch/cluster/riscv32-cluster/cluster.c
  src/hal/arch/cluster/x86-cluster/boot.S
  src/hal/arch/cluster/x86-cluster/cluster.c
  src/hal/arch/core/i486/core.c
  src/hal/arch/core/i486/setup.c
  src/hal/arch/core/or1k/core.c
  src/hal/cluster/cluster.c
  src/hal/log.c
  src/test/build/makefile.unix64
Labels: enhancement

#519 [hal] Platform Independent Setup for Virtual Memory
  include/arch/cluster/k1b-cluster/memory.h
  include/arch/cluster/linux64-cluster/memory.h
  include/arch/cluster/optimsoc-cluster/memory.h
  include/arch/cluster/or1k-cluster/memory.h
  include/arch/cluster/riscv32-cluster/memory.h
  include/arch/cluster/x86-cluster/memory.h
  include/arch/core/i486/mmu.h
  include/arch/core/k1b/mmu.h
  include/arch/core/linux64/mmu.h
  include/arch/core/or1k/mmu.h
  include/arch/core/rv32gc/mmu.h
  include/arch/core/rv32gc/tlb.h
  include/nanvix/hal/cluster/memory.h
  src/hal/arch/cluster/k1b-cluster/cluster.c
  src/hal/arch/cluster/k1b-cluster/memory.c
  src/hal/arch/cluster/linux64-cluster/memory.c
  src/hal/arch/cluster/or1k-cluster/cluster.c
  src/hal/arch/cluster/or1k-cluster/memory.c
  src/hal/arch/cluster/riscv32-cluster/cluster.c
  src/hal/arch/cluster/riscv32-cluster/memory.c
  src/hal/arch/cluster/x86-cluster/cluster.c
  src/hal/arch/cluster/x86-cluster/memory.c
  src/hal/cluster/memory.c
Labels: enhancement, mppa256, optimsoc, qemu-openrisc, qemu-riscv32, qemu-x86, unix64

#521 [hal] Sync, Mailbox and Portal Interfaces
  include/arch/processor/bostan.h
  include/arch/processor/bostan/noc/ctag.h
  include/arch/processor/bostan/noc/dtag.h
  include/arch/target/kalray/mppa256.h
  include/arch/target/kalray/mppa256/mailbox.h
  include/arch/target/kalray/mppa256/portal.h
  include/arch/target/kalray/mppa256/sync.h
  include/nanvix/hal/target.h
  include/nanvix/hal/target/_target.h
  include/nanvix/hal/target/mailbox.h
  include/nanvix/hal/target/portal.h
  include/nanvix/hal/target/sync.h
  src/hal/arch/target/mppa256/mailbox.c
  src/hal/arch/target/mppa256/portal.c
  src/hal/arch/target/mppa256/sync.c
  src/test/main.c
  src/test/target/mailbox.c
  src/test/target/sync.c
Labels: enhancement, feature

#520 Generic Exception Setup
  include/nanvix/hal/core/exception.h
  src/hal/arch/core/linux64-core/excp.c
  src/hal/core/exception.c
  src/hal/hal.c
Labels: enhancement

#525 [ha] Mailbox Dummy Interfaces Are No Longer Needed
  include/nanvix/hal/target/mailbox.h
Labels: enhancement
