Repository nanvix/hal, pull requests merged in 2019-05, with the labels that each got.

#408 [hal] Enhancement: Independent TLB implemention
  include/arch/cluster/k1b-cluster/memory.h
  include/arch/cluster/or1k-cluster/memory.h
  include/arch/core/k1b/tlb.h
  include/arch/core/or1k/tlb.h
  include/nanvix/hal/cluster/memory.h
  include/nanvix/hal/core/tlb.h
  src/hal/arch/cluster/k1b-cluster/memory.c
  src/hal/arch/cluster/or1k-cluster/memory.c
  src/hal/arch/core/k1b/tlb.c
  src/hal/arch/core/or1k/tlb.c
  src/hal/cluster/memory.c
Labels: enhancement, mppa256, optimsoc, qemu-openrisc

#411 [hal] Enhancement: Event Handler
  include/arch/core/i486/int.h
  include/arch/core/k1b/int.h
  include/arch/core/or1k/int.h
  include/arch/core/rv32gc/int.h
  include/arch/core/rv32gc/lpic.h
  include/nanvix/hal/cluster/event.h
  src/hal/core/interrupt.c
Labels: enhancement

#412 [or1k-cluster] Blocking Events
  include/arch/cluster/optimsoc-cluster.h
  include/arch/cluster/optimsoc-cluster/event.h
  include/arch/cluster/optimsoc-cluster/memory.h
  include/arch/cluster/or1k-cluster.h
  include/arch/cluster/or1k-cluster/event.h
  include/arch/cluster/or1k-cluster/memory.h
  include/arch/core/or1k/int.h
  src/hal/arch/cluster/or1k-cluster/event.c
  src/hal/arch/cluster/or1k-cluster/ompic.c
  src/hal/arch/core/or1k/hooks.S
  src/hal/arch/core/or1k/int.c
Labels: enhancement, optimsoc, qemu-openrisc

#417 [or1k-core] BSS Initialization Is Missing
  build/optimsoc/linker/link.ld
  build/qemu-openrisc/linker/link.ld
  include/arch/cluster/optimsoc-cluster/memory.h
  include/arch/cluster/or1k-cluster/memory.h
  include/arch/core/or1k/asm.h
  src/hal/arch/cluster/or1k-cluster/_cluster.S
  src/hal/arch/cluster/or1k-cluster/boot_code.S
  src/hal/arch/cluster/or1k-cluster/boot_data.S
  src/hal/arch/cluster/or1k-cluster/cluster.c
  src/hal/arch/cluster/or1k-cluster/memory.c
Labels: bug, confirmed, optimsoc, qemu-openrisc

#418 [k1b] Bugfix: Wrong Mapping of TLB
  src/hal/arch/target/mppa256/bindesc.c
Labels: bug, confirmed, mppa256

#421 [hal] Generic power off
  include/arch/cluster/k1b-cluster/cores.h
  include/nanvix/hal/core.h
  src/hal/arch/core/i486/core.c
  src/hal/arch/core/k1b/core.c
  src/hal/arch/core/or1k/core.c
  src/hal/arch/core/rv32gc/core.c
  src/hal/core/core.c
Labels: enhancement, mppa256, optimsoc, qemu-openrisc, qemu-riscv32, qemu-x86

#422 [hal] Disable Stress Tests in Default Build
  src/test/cluster/cores.c
  src/test/makefile
Labels: enhancement

#424 [optimsoc-cluster] Bug Fix: Provided Interface Not Defined
  include/arch/cluster/optimsoc-cluster/memory.h
Labels: bug, confirmed, optimsoc

#427 [optimsoc-cluster] Using the Busy-Waiting Approach in the Events
  src/hal/arch/cluster/or1k-cluster/event.c
Labels: bug, confirmed, optimsoc

#425 [hal] Core Functions on Cluster AL
  include/nanvix/hal/cluster.h
  include/nanvix/hal/core.h
  src/hal/cluster/cluster.c
  src/hal/core/core.c
Labels: enhancement, mppa256, optimsoc, qemu-openrisc, qemu-riscv32, qemu-x86

#430 [mor1kx-core] Performance Monitoring Interface
  include/arch/cluster/optimsoc-cluster/ompic.h
  include/arch/core/mor1kx.h
  include/arch/core/mor1kx/perf.h
  include/arch/core/or1k/regs.h
  src/hal/arch/core/mor1kx/perf.c
  src/hal/build/makefile.optimsoc
Labels: feature, optimsoc

#436 [hal] Wrong Padding When Forging an Upcall
  src/hal/upcall.c
  src/test/core/upcall.c
Labels: bug, confirmed, mppa256

#441 [optimsoc] Perf-Events: I/D-Cache Stalls, Register Stalls
  include/arch/core/mor1kx/perf.h
Labels: enhancement, optimsoc

#443 [optimsoc] Performance Counters Restart
  include/arch/core/mor1kx/perf.h
  src/hal/arch/core/mor1kx/perf.c
Labels: enhancement, optimsoc

#446 [k1b] Bugfix: Wrong Static TLBs entries
  src/hal/arch/target/mppa256/bindesc.c
Labels: bug, confirmed, mppa256

#448 [test] TravisCI Build Support for UNIX 64-bit
  .travis.yml
  build/unix64/make/makefile.cflags
Labels: feature, good first issue, unix64

#449 [hal] Bug Fix: Optimization Produces Wrong Code
  include/nanvix/cc.h
  src/test/cluster/cores.c
  src/test/core/interrupt.c
Labels: bug, confirmed, optimsoc, qemu-openrisc

#450 [openrisc] Optimization Flags
  build/optimsoc/make/makefile.cflags
  build/qemu-openrisc/make/makefile.cflags
Labels: bug, confirmed, optimsoc, qemu-openrisc

#429 [build] TravisCI Support for OpTiMSoC
  .travis.yml
Labels: bug, confirmed, optimsoc

#453 [openrisc] Enhancement: Cache Setup
  include/arch/core/or1k/cache.h
  src/hal/arch/cluster/or1k-cluster/boot_code.S
Labels: enhancement, optimsoc, qemu-openrisc

#454 [openrisc] Bootstrap Link Variables
  build/optimsoc/linker/link.ld
  build/qemu-openrisc/linker/link.ld
  include/arch/cluster/optimsoc-cluster/memory.h
  include/arch/cluster/or1k-cluster/memory.h
Labels: enhancement, optimsoc, qemu-openrisc
