Repository nanvix/hal, pull requests merged in 2019-06, with the labels that each got.

#483 [hal] Bad Cache Inval in Spinlock Release
  include/arch/core/i486/spinlock.h
  include/arch/core/k1b/spinlock.h
  include/arch/core/or1k/spinlock.h
  include/arch/core/rv32gc/spinlock.h
Labels: bug, confirmed, mppa256, optimsoc, qemu-openrisc, qemu-riscv32, qemu-x86

#480 [linux64-cluster] Moving Cores Interface
  include/arch/cluster/linux64-cluster/_linux64-cluster.h
  include/arch/cluster/linux64-cluster/cores.h
  include/arch/core/linux64/core.h
  src/hal/arch/cluster/linux64-cluster/boot.c
  src/hal/arch/cluster/linux64-cluster/cores.c
  src/hal/arch/cluster/linux64-cluster/memory.c
Labels: enhancement, unix64

#484 [openrisc-cluster] Wrong Spinlock Initialization
  src/hal/arch/cluster/or1k-cluster/cluster.c
Labels: bug, confirmed, optimsoc, qemu-openrisc

#477 [mppa256] Replaces LibNoC for mOS CNoC functions
  build/unix64/make/makefile
  include/arch/core/k1b/mOS.h
  include/arch/processor/bostan/noc.h
  include/arch/processor/bostan/noc/ctag.h
  include/arch/processor/bostan/noc/dma.h
  include/arch/processor/bostan/noc/dtag.h
  include/arch/processor/bostan/noc/tag.h
  include/nanvix/hal/processor/noc.h
  include/nanvix/hal/target.h
  include/nanvix/hal/target/mailbox.h
  src/build/cluster/makefile.k1b
  src/hal/arch/processor/bostan/ctag.c
  src/hal/arch/processor/bostan/dma.c
  src/hal/arch/processor/bostan/dtag.c
  src/hal/arch/target/mppa256/sync.c
  src/hal/hal.c
  src/test/main.c
  src/test/makefile
  src/test/processor/cnoc.c
  src/test/target/sync.c
  src/test/test.h
Labels: enhancement

#485 [qemu-x86] I/O Functions for 8/16/32 bits
  include/arch/core/i486/pmio.h
Labels: enhancement, qemu-x86
