Repository nanvix/hal, pull requests merged in 2019-04, with the labels that each got.

#255 [doc] Fixing Documentation Build
  include/arch/core/i486.h
  include/arch/core/i486/context.h
  include/arch/core/i486/excp.h
  include/arch/core/i486/trap.h
  include/arch/core/k1b.h
  include/arch/core/k1b/excp.h
  include/arch/core/k1b/ivt.h
  include/arch/core/k1b/pmio.h
  include/arch/core/k1b/trap.h
  include/arch/core/mor1kx.h
  include/arch/core/or1k.h
  include/arch/core/or1k/context.h
  include/arch/core/or1k/excp.h
  include/arch/core/or1k/trap.h
  include/arch/core/rv32i.h
  include/arch/core/rv32i/core.h
  include/arch/core/rv32i/excp.h
  include/arch/core/rv32i/ivt.h
  include/arch/core/rv32i/pic.h
  include/arch/core/rv32i/trap.h
  include/arch/processor/bostan/noc/ctag.h
  include/arch/processor/bostan/noc/dma.h
  include/arch/processor/bostan/noc/dtag.h
  include/arch/processor/bostan/noc/node.h
  include/arch/processor/bostan/noc/tag.h
  include/nanvix/hal/cluster/mmio.h
  include/nanvix/hal/core/context.h
  include/nanvix/hal/core/trap.h
  include/nanvix/hal/resource.h
  include/nanvix/klib.h
  src/hal/arch/core/or1k/excp.c
  src/hal/arch/core/or1k/tlb.c
  src/hal/arch/processor/bostan/dtag.c
  src/hal/arch/target/mppa256/sync.c
  src/hal/stdout/16550a.c
  src/hal/stdout/8250.c
Labels: bug, confirmed

#257 [hal] Use One Slave Core in Unit tests
  src/test/core.c
Labels: bug, confirmed

#258 Dropping Routines from Hardware Interrupt Interface
  include/nanvix/hal/core/interrupt.h
Labels: bug, confirmed

#265 [hal][lib] C Compiler Extensions
  include/nanvix/cc.h
  include/nanvix/const.h
  include/nanvix/klib.h
Labels: feature

#272 [hal] Return Value for Core Start
  include/nanvix/hal/core.h
  src/hal/core/core.c
Labels: bug, confirmed

#260 [hal][test] Stop Execution in a Slave Core
  src/test/core.c
Labels: feature

#261 [hal][test] Start Execution in Slave Core from Slave
  src/test/core.c
Labels: feature

#273 [hal] Source Tree Refactor
  include/arch/processor/bostan/noc.h
  include/arch/target/kalray/mppa256/sync.h
  include/nanvix/hal/core/cache.h
  include/nanvix/hal/core/mmu.h
  include/nanvix/hal/core/tlb.h
  include/nanvix/hal/core/trap.h
  include/nanvix/hal/processor/clusters.h
  include/nanvix/hal/processor/noc.h
  include/nanvix/hal/target/stdout.h
  include/nanvix/hal/target/sync.h
  src/test/sync.c
Labels: enhancement

#275 [bostan] Complete the DMA interface
  include/arch/processor/bostan/noc/dtag.h
  src/hal/arch/processor/bostan/dtag.c
Labels: enhancement

#281 [hal] Mailbox Interface
  include/arch/target/kalray/mppa256.h
  include/arch/target/optimsoc/optimsoc.h
  include/arch/target/qemu/i486-pc.h
  include/arch/target/qemu/or1k-pc.h
  include/arch/target/qemu/riscv32.h
  include/nanvix/hal/target/mailbox.h
Labels: feature, mppa256, optimsoc, qemu-openrisc, qemu-riscv32, qemu-x86

#274 [rv32i] Machine Hypervisor
  build/qemu-riscv32/linker/link.ld
  include/arch/cluster/riscv32-smp/_riscv32-smp.h
  include/arch/core/rv32i/asm.h
  include/arch/core/rv32i/cache.h
  include/arch/core/rv32i/clock.h
  include/arch/core/rv32i/core.h
  include/arch/core/rv32i/excp.h
  include/arch/core/rv32i/int.h
  include/arch/core/rv32i/ivt.h
  include/arch/core/rv32i/mcall.h
  include/arch/core/rv32i/mmu.h
  include/arch/core/rv32i/pic.h
  include/arch/core/rv32i/regs.h
  include/arch/core/rv32i/spinlock.h
  include/arch/core/rv32i/trap.h
  include/arch/core/rv32i/types.h
  include/nanvix/const.h
  include/nanvix/klib.h
  src/hal/arch/core/rv32i/boot.S
  src/hal/arch/core/rv32i/clock.c
  src/hal/arch/core/rv32i/excp.c
  src/hal/arch/core/rv32i/hooks.S
  src/hal/arch/core/rv32i/int.c
  src/hal/arch/core/rv32i/ivt.c
  src/hal/arch/core/rv32i/machine.c
  src/hal/arch/core/rv32i/pic.c
  src/hal/arch/core/rv32i/setup.c
  src/hal/stdout/16550a.c
  src/test/main.c
Labels: feature, qemu-riscv32

#282 [rv32i] MMU Interface
  include/arch/core/rv32i/mmu.h
Labels: feature, qemu-riscv32

#283 [rv32i] TLB Interface
  include/arch/core/rv32i.h
  include/arch/core/rv32i/tlb.h
Labels: feature, qemu-riscv32

#284 [hal][test] Enhancement: Suspend and Resume from Slave
  src/test/core.c
Labels: feature

#287 [hal][lib] Builtins Likely and Unlikely
  include/nanvix/cc.h
Labels: enhancement

#289 [hal] Refactoring Memory Interface
  include/arch/cluster/k1b-cluster.h
  include/arch/cluster/k1b-cluster/_k1b-cluster.h
  include/arch/cluster/k1b-cluster/cores.h
  include/arch/cluster/k1b-cluster/memory.h
  include/arch/cluster/or1k-cluster.h
  include/arch/cluster/or1k-cluster/_or1k-cluster.h
  include/arch/cluster/or1k-cluster/cores.h
  include/arch/cluster/or1k-cluster/memory.h
  include/arch/cluster/or1k/memory.h
  include/arch/cluster/riscv32-cluster.h
  include/arch/cluster/riscv32-cluster/_riscv32-cluster.h
  include/arch/cluster/riscv32-cluster/cores.h
  include/arch/cluster/x86-cluster.h
  include/arch/cluster/x86-cluster/_x86-cluster.h
  include/arch/cluster/x86-cluster/cores.h
  include/arch/cluster/x86-cluster/memory.h
  include/arch/core/i486.h
  include/arch/core/i486/clock.h
  include/arch/core/i486/int.h
  include/arch/core/i486/pic.h
  include/arch/core/k1b/pmio.h
  include/arch/processor/bostan/_bostan.h
  include/arch/processor/i486-qemu/_i486-qemu.h
  include/arch/processor/or1k-qemu/_or1k-qemu.h
  include/arch/processor/riscv32/_riscv32.h
  include/nanvix/hal/cluster/_cluster.h
  include/nanvix/hal/cluster/memory.h
  src/build/cluster/makefile.k1b
  src/build/processor/makefile.optimsoc
  src/build/processor/makefile.or1k
  src/build/processor/makefile.riscv32
  src/build/processor/makefile.x86
  src/hal/arch/cluster/k1b-cluster/memory.c
  src/hal/arch/cluster/or1k-cluster/boot_code.S
  src/hal/arch/cluster/or1k-cluster/boot_data.S
  src/hal/arch/cluster/or1k-cluster/memory.c
  src/hal/arch/cluster/or1k-cluster/ompic.c
  src/hal/arch/cluster/x86-cluster/boot.S
  src/hal/arch/core/i486/clock.c
  src/hal/arch/core/i486/core.c
  src/hal/arch/core/i486/hooks.S
  src/hal/arch/core/i486/idt.c
  src/hal/arch/core/i486/pic.c
  src/hal/arch/core/i486/tss.c
  src/hal/arch/core/k1b/_core.S
  src/hal/arch/core/k1b/ivt.c
  src/hal/arch/core/k1b/tlb.c
  src/hal/arch/core/or1k/core.c
  src/hal/arch/core/or1k/tlb.c
  src/hal/makefile
  src/test/mmu.c
  src/test/tlb.c
Labels: enhancement, mppa256, qemu-openrisc, qemu-x86

#291 [hal] Bug Fix: No One Core Should Start Itself
  src/hal/core/core.c
Labels: bug

#298 [x86-qemu] Disabling Unit Tests for Core Interface
  include/arch/cluster/x86-cluster.h
  src/test/main.c
Labels: bug

#299 [hal] Checking Function Pointer Before Start
  src/hal/core/core.c
Labels: bug

#300 [hal][test] Start a Bad Execution Flow
  src/test/core.c
Labels: feature

#301 [hal] Bug Fix: Checking Core ID Before Start
  src/hal/core/core.c
Labels: bug

#302 [hal][test] Starts an Invalid Execution Flow
  src/test/core.c
Labels: feature

#303 [hal] Master Core is Not Allowed to Reset
  include/nanvix/hal/core.h
  src/hal/core/core.c
Labels: bug

#304 [hal][test] Stop Instruction Execution in the Master Core
  src/test/core.c
Labels: feature

#305 [rv32i] Memory Barrier of Spinlock Initialization
  include/arch/core/rv32i/spinlock.h
Labels: bug, qemu-riscv32

#306 [riscv32] Bad Import Symbols
  include/arch/cluster/riscv32-cluster.h
  include/arch/processor/riscv32/_riscv32.h
  include/nanvix/hal/cluster/_cluster.h
Labels: bug, qemu-riscv32

#307 [qemu-riscv32] Overriding LDFLAGS
  build/qemu-riscv32/make/makefile
Labels: bug, qemu-riscv32

#308 [hal][lib] Missing Assembler Guard for stdint
  include/stdint.h
Labels: bug

#309 [qemu-riscv32] Use Lib GCC for Math
  build/qemu-riscv32/make/makefile
  src/hal/build/makefile.qemu-riscv32
Labels: enhancement, qemu-riscv32

#310 [hal] Invalid Core Should Not Resume
  include/nanvix/hal/core.h
  src/hal/core/core.c
Labels: bug

#311 [hal][test] Resume Instruction Execution in an Invalid Core
  src/test/core.c
Labels: feature

#312 [hal] Bad Core Should Not Resume
  src/hal/core/core.c
Labels: bug

#314 [test] Bad Check for Core ID
  src/hal/core/core.c
Labels: bug

#323 [or1k-core] Bug Fix: Using Spinlocks Builtins
  include/arch/core/or1k/spinlock.h
  include/arch/core/rv32i/spinlock.h
Labels: bug

#331 [rv32i] Enabling Unit Tests for TLB and MMU Interfaces
  include/arch/core/rv32i/mmu.h
  src/hal/build/makefile.qemu-riscv32
  src/test/build/makefile.qemu-riscv32
  src/test/main.c
Labels: bug, confirmed, qemu-riscv32

#334 [optimsoc] Bug Fix: Wrong Cluster Header
  include/arch/processor/optimsoc/_optimsoc.h
Labels: bug, optimsoc, qemu-openrisc

#335 [or1k-core] Calibrate the Timer of Clock Device
  src/hal/arch/core/or1k/clock.c
Labels: enhancement, optimsoc, qemu-openrisc

#340 [or1k] Enhancement: Extensions for MMU Interface
  include/arch/core/or1k/mmu.h
  include/arch/core/or1k/types.h
  src/hal/arch/core/or1k/mmu.c
Labels: enhancement, optimsoc, qemu-openrisc

#346 Enhancement: LPIC Interface Refactor
  include/arch/core/i486.h
  include/arch/core/i486/int.h
  include/arch/core/i486/lpic.h
  include/arch/core/i486/pic.h
  include/arch/core/i486/pmio.h
  include/arch/core/k1b/context.h
  include/arch/core/k1b/int.h
  include/arch/core/k1b/lpic.h
  include/arch/core/or1k.h
  include/arch/core/or1k/int.h
  include/arch/core/or1k/lpic.h
  include/arch/core/or1k/pic.h
  include/arch/core/rv32i/context.h
  include/arch/core/rv32i/int.h
  include/arch/core/rv32i/ivt.h
  include/arch/core/rv32i/lpic.h
  include/nanvix/hal/core/interrupt.h
  src/hal/arch/core/i486/hooks.S
  src/hal/arch/core/i486/idt.c
  src/hal/arch/core/i486/lpic.c
  src/hal/arch/core/i486/setup.c
  src/hal/arch/core/k1b/int.c
  src/hal/arch/core/k1b/lpic.c
  src/hal/arch/core/or1k/core.c
  src/hal/arch/core/or1k/hooks.S
  src/hal/arch/core/or1k/int.c
  src/hal/arch/core/or1k/lpic.c
  src/hal/arch/core/or1k/pic.c
  src/hal/arch/core/rv32i/int.c
  src/hal/arch/core/rv32i/lpic.c
  src/hal/core/exception.c
Labels: enhancement, mppa256, optimsoc, qemu-openrisc, qemu-riscv32, qemu-x86

#350 Renaming Context Interface Headers
  include/arch/core/i486/asm.h
  include/arch/core/i486/ctx.h
  include/arch/core/i486/excp.h
  include/arch/core/k1b/asm.h
  include/arch/core/k1b/ctx.h
  include/arch/core/k1b/excp.h
  include/arch/core/k1b/int.h
  include/arch/core/or1k/asm.h
  include/arch/core/or1k/ctx.h
  include/arch/core/or1k/excp.h
  include/arch/core/rv32i/asm.h
  include/arch/core/rv32i/ctx.h
  include/arch/core/rv32i/excp.h
  include/arch/core/rv32i/int.h
  include/arch/core/rv32i/machine.h
  src/hal/arch/core/i486/_upcall.S
  src/hal/arch/core/i486/ctx.c
  src/hal/arch/core/i486/hooks.S
  src/hal/arch/core/k1b/_upcall.S
  src/hal/arch/core/k1b/ctx.c
  src/hal/arch/core/k1b/hooks.S
  src/hal/arch/core/k1b/int.c
  src/hal/arch/core/k1b/ivt.c
  src/hal/arch/core/or1k/_upcall.S
  src/hal/arch/core/or1k/ctx.c
  src/hal/arch/core/rv32i/ctx.c
  src/hal/arch/core/rv32i/machine.c
Labels: enhancement, mppa256, optimsoc, qemu-openrisc, qemu-riscv32, qemu-x86

#352 [hal] Core Features
  include/arch/core/i486.h
  include/arch/core/i486/tlb.h
  include/arch/core/k1b.h
  include/arch/core/k1b/tlb.h
  include/arch/core/mor1kx.h
  include/arch/core/or1k.h
  include/arch/core/or1k/tlb.h
  include/arch/core/rv32i.h
  include/arch/core/rv32i/tlb.h
  include/nanvix/hal/core/exception.h
  include/nanvix/hal/core/pmio.h
  include/nanvix/hal/core/tlb.h
  src/test/tlb.c
Labels: enhancement, mppa256, optimsoc, qemu-openrisc, qemu-riscv32, qemu-x86

#354 [build] Pretty Build
  build/qemu-riscv32/make/makefile
  include/nanvix/hal/core/cache.h
  include/nanvix/hal/core/clock.h
  include/nanvix/hal/core/context.h
  include/nanvix/hal/core/exception.h
  include/nanvix/hal/core/interrupt.h
  include/nanvix/hal/core/mmu.h
  include/nanvix/hal/core/pmio.h
  include/nanvix/hal/core/spinlock.h
  include/nanvix/hal/core/tlb.h
  include/nanvix/hal/core/trap.h
  include/nanvix/hal/core/upcall.h
  makefile
  src/build/makefile.nanvix
  src/build/processor/makefile.bostan
  src/hal/build/makefile.mppa256
  src/hal/build/makefile.optimsoc
  src/hal/build/makefile.qemu-openrisc
  src/hal/build/makefile.qemu-riscv32
  src/hal/build/makefile.qemu-x86
  src/hal/makefile
  src/test/build/makefile.mppa256
  src/test/build/makefile.qemu-openrisc
  src/test/build/makefile.qemu-riscv32
  src/test/build/makefile.qemu-x86
  src/test/makefile
Labels: enhancement

#355 [test] Hierarchical Unit tests
  src/test/build/makefile.mppa256
  src/test/build/makefile.qemu-openrisc
  src/test/build/makefile.qemu-riscv32
  src/test/build/makefile.qemu-x86
  src/test/core/arch/i486.S
  src/test/core/arch/k1b.S
  src/test/core/arch/or1k.S
  src/test/core/core.c
  src/test/core/exception.c
  src/test/core/interrupt.c
  src/test/core/mmu.c
  src/test/core/syscalls.c
  src/test/core/tlb.c
  src/test/core/upcall.c
  src/test/main.c
  src/test/processor/sync.c
Labels: enhancement

#372 [rv32gc] Re-Enabling Trap Interface
  include/arch/core/rv32gc/asm.h
  include/arch/core/rv32gc/trap.h
  src/hal/arch/core/rv32gc/hooks.S
  src/test/main.c
Labels: enhancement, qemu-riscv32

#384 [rv32gc] Dump Supervisor Registers
  src/hal/arch/core/rv32gc/ctx.c
  src/hal/core/exception.c
Labels: enhancement, qemu-riscv32

#385 [hal] Bad Sizes for Memory Regions
  include/arch/cluster/or1k-cluster/memory.h
  include/arch/cluster/riscv32-cluster/memory.h
Labels: bug, confirmed, qemu-openrisc, qemu-riscv32

#386 [k1b] Bugfix: TLB initializer
  include/arch/core/k1b/tlb.h
Labels: bug, confirmed, mppa256

#387 [or1k] Using the Frequency Supplied to Initialize Clock
  include/arch/cluster/optimsoc-cluster/clock.h
  include/arch/cluster/or1k-cluster/clock.h
  include/arch/core/mor1kx/clock.h
  include/arch/core/or1k/clock.h
  src/hal/arch/core/or1k/clock.c
Labels: bug, confirmed, optimsoc, qemu-openrisc

#388 [i486] MMU Extensions
  include/arch/core/i486/mmu.h
  include/arch/core/i486/types.h
  src/hal/arch/core/i486/mmu.c
Labels: enhancement, qemu-x86

#389 [k1b-core] Trashing Context in Exception
  include/arch/core/k1b/asm.h
  src/hal/arch/core/k1b/hooks.S
  src/test/core/arch/k1b.S
Labels: bug, confirmed, mppa256

#390 [hal] Missing MMU Operations
  include/arch/core/i486.h
  include/arch/core/i486/mmu.h
  include/arch/core/k1b.h
  include/arch/core/k1b/mmu.h
  include/arch/core/mor1kx.h
  include/arch/core/or1k.h
  include/arch/core/or1k/mmu.h
  include/arch/core/rv32gc.h
  include/arch/core/rv32gc/mmu.h
  include/nanvix/hal/core/mmu.h
Labels: bug, confirmed, mppa256, optimsoc, qemu-openrisc, qemu-riscv32, qemu-x86

#392 [test] Stress Tests for Cores Interface
  src/test/cluster/cores.c
  src/test/core/core.c
  src/test/main.c
  src/test/makefile
  src/test/test.h
Labels: enhancement

#395 [hal] Enhancement: Move TLB Management to Cluster AL
  include/arch/cluster/k1b-cluster/memory.h
  include/arch/cluster/or1k-cluster/memory.h
  include/arch/core/k1b/tlb.h
  include/arch/core/or1k/tlb.h
  include/nanvix/hal/cluster/memory.h
  include/nanvix/hal/core/tlb.h
  src/hal/arch/cluster/k1b-cluster/memory.c
  src/hal/arch/cluster/or1k-cluster/memory.c
  src/hal/arch/core/k1b/tlb.c
  src/hal/arch/core/or1k/tlb.c
Labels: enhancement, mppa256, optimsoc, qemu-openrisc

#402 [or1k] Splitting OpenRISC Clusters
  include/arch/cluster/optimsoc-cluster/cores.h
  include/arch/cluster/optimsoc-cluster/memmap.h
  include/arch/cluster/optimsoc-cluster/memory.h
  include/arch/cluster/optimsoc-cluster/ompic.h
  include/arch/cluster/or1k-cluster/memmap.h
  include/arch/cluster/or1k-cluster/memory.h
  include/arch/cluster/or1k-cluster/ompic.h
  src/hal/arch/cluster/optimsoc-cluster/_cluster.S
  src/hal/arch/cluster/optimsoc-cluster/boot_code.S
  src/hal/arch/cluster/optimsoc-cluster/boot_data.S
  src/hal/arch/cluster/optimsoc-cluster/cluster.c
  src/hal/arch/cluster/optimsoc-cluster/event.c
  src/hal/arch/cluster/optimsoc-cluster/memory.c
  src/hal/arch/cluster/optimsoc-cluster/ompic.c
  src/hal/arch/cluster/or1k-cluster/boot_code.S
  src/hal/arch/cluster/or1k-cluster/boot_data.S
  src/hal/arch/cluster/or1k-cluster/cluster.c
  src/hal/arch/cluster/or1k-cluster/event.c
  src/hal/arch/cluster/or1k-cluster/memory.c
  src/hal/arch/cluster/or1k-cluster/ompic.c
  src/hal/build/makefile.optimsoc
Labels: enhancement, optimsoc, qemu-openrisc
