Repository nanvix/hal, pull requests merged in 2019-03, with the labels that each got.

#54 Bug Fix: Out of Date Run Script
  .gdbinit
  build/i386-pc/make/makefile
  build/or1k-pc/make/makefile
  src/test/build/makefile.i386-pc
  src/test/build/makefile.or1k-pc
  tools/run/run-qemu.sh
Labels: bug, openrisc-qemu, x86-qemu

#64 [or1k-qemu] Bug Fix: Bad Link Script
  build/or1k-pc/linker/link.ld
Labels: bug, confirmed, openrisc-qemu

#86 [k1b-core] Enhancement: Procedure Linkage
  include/arch/core/k1b/asm.h
  src/hal/arch/core/k1b/hooks.S
Labels: enhancement, mppa256

#90 [hal] Enhancement: Start Instruction Execution in a Slave Core
  src/test/clock.c
  src/test/core.c
  src/test/main.c
Labels: enhancement, mppa256, openrisc-qemu, optimsoc, x86-qemu

#99 [hal] Enhancement: Auto-Name Reserved Fields
  include/nanvix/klib.h
Labels: enhancement

#113 [hal] Enhancement: Suspend and Resume from Master
  src/test/core.c
Labels: feature

#121 [test] Travis CI Build Support
  .travis.yml
Labels: feature, openrisc-qemu, x86-qemu

#114 [hal Exporting Memory Types
  include/arch/core/i386/mmu.h
  include/arch/core/i386/types.h
  include/arch/core/k1b/mmu.h
  include/arch/core/k1b/types.h
  include/arch/core/or1k/mmu.h
  include/arch/core/or1k/types.h
  include/nanvix/hal/core/mmu.h
Labels: enhancement, mppa256, openrisc-qemu, optimsoc, x86-qemu

#115 [hal] Trap Interface
  include/arch/core/i386.h
  include/arch/core/i386/idt.h
  include/arch/core/i386/int.h
  include/arch/core/i386/trap.h
  include/arch/core/k1b.h
  include/arch/core/k1b/trap.h
  include/arch/core/or1k.h
  include/arch/core/or1k/trap.h
  include/nanvix/hal/core.h
  include/nanvix/hal/core/trap.h
  src/hal/arch/core/i386/hooks.S
  src/hal/arch/core/i386/idt.c
  src/hal/arch/core/k1b/hooks.S
  src/hal/arch/core/or1k/hooks.S
  src/test/syscalls.c
Labels: feature, mppa256, openrisc-qemu, optimsoc, x86-qemu

#122 [i386-core] Feature: Spinlock Interface
  include/arch/core/i386/spinlock.h
Labels: feature, x86-qemu

#125 [or1k-core] Locking Same Entry of Cores Table 2x
  src/hal/arch/core/or1k/core.c
Labels: bug, confirmed, openrisc-qemu, optimsoc

#127 [hal][test] Unit Test Driver for Trap Interface
  src/test/main.c
  src/test/syscalls.c
  src/test/test.h
Labels: feature

#134 [hal] Platform-Independent Core Interface Implementation
  include/arch/core/i486/core.h
  include/arch/core/k1b/core.h
  include/arch/core/or1k/cache.h
  include/arch/core/or1k/core.h
  include/arch/core/or1k/pic.h
  include/arch/core/or1k/regs.h
  include/nanvix/hal/core.h
  src/hal/arch/core/i486/core.c
  src/hal/arch/core/k1b/core.c
  src/hal/arch/core/k1b/setup.c
  src/hal/arch/core/or1k/core.c
  src/hal/arch/core/or1k/setup.c
  src/hal/core/core.c
  src/hal/core/interrupt.c
  src/hal/makefile
  src/test/core.c
Labels: enhancement, mppa256, openrisc-qemu, optimsoc, x86-qemu

#135 Size Checking of Exception and Context Structures
  include/arch/core/or1k/context.h
  src/hal/hal.c
Labels: enhancement

#158 [build] Adding Travis CI Integration with Slack
  .travis.yml
Labels: enhancement

#145 [k1b-core] Bad Interrupt Masking
  include/arch/core/k1b/pic.h
Labels: bug, confirmed, mppa256

#146 [hal] Unmask Clock Interrupt
  include/arch/core/or1k/pic.h
  src/test/clock.c
Labels: bug, confirmed

#151 [hal][lib] Buffer Size Too Small
  include/nanvix/klib.h
Labels: bug, confirmed

#152 [hal] Enhancements in the Hardware Interrupt Interface
  include/arch/core/i486/8259.h
  include/arch/core/i486/int.h
  include/arch/core/k1b/int.h
  include/arch/core/k1b/pic.h
  include/arch/core/or1k/int.h
  include/arch/core/or1k/pic.h
  include/nanvix/hal/core/interrupt.h
  src/hal/arch/core/i486/8259.c
  src/hal/arch/core/i486/clock.c
  src/hal/arch/core/i486/hwint.c
  src/hal/arch/core/k1b/hwint.c
  src/hal/arch/core/or1k/hwint.c
  src/hal/core/interrupt.c
Labels: enhancement, mppa256, optimsoc, qemu-openrisc, qemu-x86

#153 [hal][test] Unit Tests for Hardware Interrupt Interface
  include/nanvix/klib.h
  src/hal/log.c
  src/test/clock.c
  src/test/interrupt.c
  src/test/main.c
  src/test/test.h
Labels: feature

#156 [hal] Enhancements in the Exception Interface
  include/arch/core/i486/excp.h
  include/arch/core/k1b/excp.h
  include/arch/core/or1k/excp.h
  include/nanvix/hal/core/exception.h
  src/hal/arch/core/i486/excp.c
  src/hal/arch/core/k1b/excp.c
  src/hal/arch/core/or1k/excp.c
Labels: enhancement, mppa256, optimsoc, qemu-openrisc, qemu-x86

#157 [hal][test] Unit Tests for Exception Interface
  src/test/exception.c
Labels: feature

#162 Enhancement: Drop Some Useless QEMU Targets
  tools/dev/setup-qemu.sh
Labels: enhancement

#163 [build] Cleanup OpenRISC Toolchain
  tools/dev/arch/or1k.sh
Labels: enhancement, optimsoc, qemu-openrisc

#164 Adding a README File
  README.md
Labels: feature

#165 [or1k-core] Bug Fix: Outdated Number of Syscalls Arguments
  src/hal/arch/core/or1k/hooks.S
Labels: bug, confirmed, optimsoc, qemu-openrisc

#166 [or1k-core] Properly Resetting Core
  include/arch/core/or1k/asm.h
  src/hal/arch/core/or1k/_core.S
  src/hal/arch/core/or1k/hooks.S
Labels: bug, confirmed

#167 [or1k-core] Enhancement: ASM Macros
  include/arch/core/or1k/asm.h
Labels: enhancement, good first issue, optimsoc, qemu-openrisc

#168 [k1b-core] Save Preserved Regs in Trap
  src/hal/arch/core/k1b/hooks.S
Labels: bug, confirmed, mppa256

#169 [k1b-core] Bad Trap Call Arguments
  src/hal/arch/core/k1b/hooks.S
Labels: bug, confirmed, mppa256

#177 [or1k-cluster] Bad KBASE_PHYS Export
  include/arch/cluster/or1k/memory.h
Labels: bug, confirmed, optimsoc, qemu-openrisc

#178 [k1b-core] Dont Trash In-Memory TLB
  src/hal/arch/core/k1b/tlb.c
Labels: bug, confirmed, mppa256

#184 [or1k-core] Bug Fix: Wrong Permissions in TLB Entry
  src/hal/arch/core/or1k/tlb.c
Labels: bug, confirmed, optimsoc, qemu-openrisc

#187 [hal] Kernel Page Size
  include/arch/core/i486/mmu.h
  include/arch/core/k1b/mmu.h
  include/arch/core/or1k/mmu.h
  include/nanvix/hal/core/mmu.h
Labels: enhancement, mppa256, optimsoc, qemu-openrisc, qemu-x86

#188 [or1k-core] Bug Fix: Checking TLB Types
  include/arch/core/or1k/tlb.h
Labels: bug, confirmed, optimsoc, qemu-openrisc

#181 [hall][test] Fault Injection Tests for TLB Interface
  include/arch/cluster/k1b/memory.h
  include/nanvix/hal/cluster.h
  src/test/tlb.c
Labels: enhancement

#185 [k1b-core] Reset Registers when Resetting the Core
  include/arch/core/k1b/asm.h
  src/hal/arch/core/k1b/_core.S
  src/hal/arch/core/k1b/hooks.S
Labels: enhancement, mppa256

#239 [hal] Auto Mask/Unmask Interrupts
  src/hal/core/interrupt.c
Labels: enhancement

#240 [hal] Track Spurious Interrupts
  include/nanvix/hal/core/interrupt.h
  src/hal/core/interrupt.c
Labels: enhancement
