Repository nanvix/hal, pull requests merged in 2019-09, with the labels that each got.

#532 [hal] Unit tests for Sync Interface
  src/test/target/sync.c
Labels: enhancement, mppa256, unix64

#533 [hal] Feature: Dynamic Initialization for Sync, Mailbox and Portal
  include/arch/target/kalray/mppa256/mailbox.h
  include/arch/target/kalray/mppa256/portal.h
  include/arch/target/kalray/mppa256/sync.h
  include/arch/target/unix64/unix64/mailbox.h
  include/arch/target/unix64/unix64/portal.h
  include/arch/target/unix64/unix64/sync.h
  include/nanvix/hal/target/mailbox.h
  include/nanvix/hal/target/portal.h
  include/nanvix/hal/target/sync.h
  src/hal/hal.c
Labels: feature, mppa256, unix64

#536 [k1b] Bugfix: Removes __builtin_k1_dflush call.
  include/arch/core/k1b/cache.h
Labels: bug, confirmed, mppa256

#537 [hal] Exchange of Node Number
  include/arch/processor/bostan/noc.h
  include/arch/processor/linux64/noc.h
  include/nanvix/hal/processor/noc.h
  src/hal/arch/processor/bostan/noc.c
  src/hal/arch/processor/linux64/noc.c
  src/hal/arch/target/unix64/mailbox.c
  src/hal/arch/target/unix64/portal.c
  src/hal/arch/target/unix64/sync.c
  src/test/processor/cnoc.c
  src/test/processor/dnoc.c
  src/test/processor/noc.c
Labels: feature, mppa256, unix64

#538 [qemu-x86] Bad Page Fault Exception Export
  include/arch/core/i486/excp.h
Labels: bug, confirmed, qemu-x86

#539 [k1b] Bug fix: No masking interrupts in NoC handler.
  src/hal/arch/processor/bostan/ctag.c
  src/hal/arch/processor/bostan/dtag.c
Labels: bug, confirmed, mppa256

#540 [mppa256] Bad Behavior of Portal Allow
  src/hal/arch/target/mppa256/portal.c
Labels: bug, confirmed

#541 [unix64] Rename Sync, Mailboxes & Portals
  src/hal/arch/target/unix64/mailbox.c
  src/hal/arch/target/unix64/portal.c
  src/hal/arch/target/unix64/sync.c
Labels: enhancement, unix64
