Repository nanvix/hal, pull requests merged in 2020-07, with the labels that each got.

#605 [mppa256] Remove Nested Interrupts and Interference Between NoC Handlers
  include/arch/processor/bostan/noc.h
  include/arch/processor/bostan/noc/ctag.h
  src/hal/arch/processor/bostan/ctag.c
  src/hal/arch/processor/bostan/dtag.c
  src/hal/arch/target/mppa256/mailbox.c
  src/hal/arch/target/mppa256/portal.c
  src/hal/arch/target/mppa256/sync.c
Labels: bug, mppa256

#609 [core-al] Bad Width for Words
  include/arch/core/linux64/types.h
Labels: bug, unix64

#610 [mppa256] Change Hash Structure to Use Primitive Types
  src/hal/arch/target/mppa256/sync.c
Labels: bug
