Repository nanvix/hal, pull requests merged in 2020-05, with the labels that each got.

#581 [target] Enhancement: Increases the mailbox size
  include/arch/target/kalray/mppa256/mailbox.h
  include/arch/target/unix64/unix64/mailbox.h
Labels: enhancement

#582 [unix64] Sync Facility Refactor
  include/arch/processor/bostan/noc.h
  include/arch/processor/bostan/noc/ctag.h
  include/arch/processor/bostan/noc/dma.h
  include/arch/target/kalray/mppa256/sync.h
  include/arch/target/unix64/unix64/sync.h
  include/nanvix/hal/target/sync.h
  src/hal/arch/processor/bostan/ctag.c
  src/hal/arch/processor/bostan/dma.c
  src/hal/arch/processor/bostan/noc.c
  src/hal/arch/target/mppa256/sync.c
  src/hal/arch/target/unix64/sync.c
  src/hal/target/sync.c
Labels: enhancement

#584 [target] Missing Constants and Checks
  include/arch/target/kalray/mppa256/mailbox.h
  include/arch/target/kalray/mppa256/portal.h
  include/arch/target/unix64/unix64/mailbox.h
  include/arch/target/unix64/unix64/portal.h
  include/nanvix/hal/target/mailbox.h
  include/nanvix/hal/target/portal.h
  include/nanvix/hal/target/sync.h
  src/hal/target/portal.c
Labels: bug, enhancement, mppa256, unix64

#585 [cluster] Core Reset in Two Phases
  build/qemu-riscv32/make/makefile
  include/nanvix/hal/cluster.h
  src/hal/cluster/cluster.c
  src/test/cluster/cores.c
Labels: bug, confirmed

#590 [hal] Extensions for Resource Abstraction
  include/nanvix/hal/resource.h
Labels: enhancement

#593 [unix64] Don't Drop Signals in the Sync Module
  src/hal/arch/target/unix64/sync.c
Labels: bug, confirmed
