Repository nanvix/hal, pull requests merged in 2020-04, with the labels that each got.

#577 Merge Dev with Unstable
  include/arch/processor/bostan/clusters.h
  include/arch/processor/linux64/clusters.h
  include/nanvix/hal/processor/clusters.h
  src/hal/arch/target/mppa256/mailbox.c
Labels: bug, confirmed, enhancement

#579 [test] Stress Tests for Communication Abstractions
  img/unix64.img
  src/test/main.c
  src/test/makefile
  src/test/stress/barrier.c
  src/test/stress/barrier.h
  src/test/stress/combination.c
  src/test/stress/mailbox.c
  src/test/stress/portal.c
  src/test/target/mailbox.c
  src/test/target/portal.c
  src/test/target/sync.c
  src/test/test.h
Labels: feature

#575 [unix64] Mailbox Non-blocking Read/Write
  src/hal/arch/target/unix64/mailbox.c
  src/test/stress/mailbox.c
Labels: bug, confirmed, unix64

#574 [unix64] Portal Non-Blocking Read/Write
  src/hal/arch/target/unix64/portal.c
Labels: bug, confirmed, unix64

#580 [unix] Bugfix: Insecure optimizations
  build/unix64/make/makefile.cflags
Labels: bug
