Repository nanvix/hal, pull requests merged in 2021-01, with the labels that each got.

#628 [test] Unit Tests Get Stuck in Unix
  src/test/main.c
Labels: bug, unix64

#635 [cores][unix64] Linux Cores Num
  include/arch/cluster/linux64-cluster/cores.h
Labels: enhancement, unix64

#637 [core] Add a Getter to Interrupt Level and Use It on Section Guards
  include/arch/core/i486/int.h
  include/arch/core/i486/lpic.h
  include/arch/core/k1b/int.h
  include/arch/core/k1b/lpic.h
  include/arch/core/linux64/int.h
  include/arch/core/or1k/int.h
  include/arch/core/or1k/lpic.h
  include/arch/core/rv32gc/int.h
  include/nanvix/hal/core/interrupt.h
  include/nanvix/hal/section_guard.h
  src/hal/arch/core/i486/lpic.c
  src/hal/arch/core/k1b/lpic.c
  src/hal/arch/core/linux64-core/int.c
  src/hal/arch/core/or1k/lpic.c
  src/hal/cluster/cluster.c
Labels: bug, confirmed, enhancement
